import { UserLdap} from './user-ldap';

export const LDAP_USERS: UserLdap[] = [
  {
    login: 'test.v1',
    nom: 'V1',
    prenom: 'Test',
    nomComplet: 'V1 Test',
    motDePass: null,
    mail: 'test.v1@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 1234,
    employeNiveau: 120,
    dateEmbauche: '2020-01-01',
    publisherId: 1,
    active: true,
  }, {
    login: 'test.v2',
    nom: 'V2',
    prenom: 'Test',
    nomComplet: 'V2 Test',
    motDePass: null,
    mail: 'test.v2@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 2234,
    employeNiveau: 220,
    dateEmbauche: '2020-02-02',
    publisherId: 2,
    active: true,
  }, {
    login: 'test.v3',
    nom: 'V3',
    prenom: 'Test',
    nomComplet: 'V3 Test',
    motDePass: null,
    mail: 'test.v3@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 3234,
    employeNiveau: 320,
    dateEmbauche: '2020-02-03',
    publisherId: 3,
    active: true,
  }, {
    login: 'test.v4',
    nom: 'V4',
    prenom: 'Test',
    nomComplet: 'V4 Test',
    motDePass: null,
    mail: 'test.v4@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 4234,
    employeNiveau: 420,
    dateEmbauche: '2020-02-04',
    publisherId: 3,
    active: true,
  }
];
